version: '3'

services:
  todofront:
    image: todofrontend
    restart: on-failure
    ports:
      - 3000:3000
    depends_on: 
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
  
  todoback:
    image: todobackend
    restart: on-failure
    ports:
      - 3001:3001

  todotests:
    image: todotests
    restart: on-failure
    depends_on: 
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront

    
